name: CI

on: [push]

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: swiftlint
    - name: Build for macOS
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
    - name: Run iOS tests
      run: sh ./scripts/ci.sh
